# Generated by Django 4.2 on 2023-05-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Название')),
                ('address', models.TextField(db_index=True, verbose_name='Адрес')),
                ('description', models.TextField(db_index=True, verbose_name='Описание')),
                ('price', models.IntegerField(blank=True, db_index=True, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='images/hotels/% Y/% m/% d/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Имя')),
                ('grade', models.IntegerField(blank=True, db_index=True, verbose_name='Оценка')),
                ('review', models.TextField(db_index=True, verbose_name='Отзыв')),
                ('image', models.ImageField(upload_to='images/reviewers/% Y/% m/% d/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Название')),
                ('description', models.TextField(db_index=True, verbose_name='Описание тура')),
                ('price', models.IntegerField(blank=True, db_index=True, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='images/tours/% Y/% m/% d/', verbose_name='Изображение')),
            ],
        ),
    ]
